package com.xanderfehsenfeld.swearjar;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

/**
 * Created by Xander on 2/6/16.
 *
 * Analyze string output from text output for swearwords and count them
 *
 *      depending on whether the phone censors swearwords, the bad words will either
 *      contain '*'s or not, so the function accounts for both by storing a bunch of bad words:
 */
public class SpeechAnalyzer {


    /* grade the dirtiness of your diction */
    public static int analyzeSpeech(String input){
        /* count number of censored words */
        String[] words = input.split(" ");
        String currWord = "";
        int count = 0;
        for (int i = 0; i < words.length; i ++){
            currWord = words[i];
            if (currWord.contains("*") || badWordsMap.containsKey(currWord)){
                count ++;
            }
        }
        return count;
    }

    /* get the bad words */
    public static ArrayList<String> getBadWords(String input){
                /* count number of censored words */
        String[] words = input.split(" ");
        String currWord = "";

        ArrayList<String> badwords = new ArrayList<>();

        for (int i = 0; i < words.length; i ++){
            currWord = words[i];
            if (currWord.contains("*") || badWordsMap.containsKey(currWord)){
                badwords.add(currWord);
            }
        }
        return badwords;
    }


    /* mapping of bad words */
    public static Map<String, Boolean> badWordsMap = new HashMap<String, Boolean>()
    {{
            put("2 girls 1 cup", true);
            put("acrotomophilia", true);
            put("alabama hot pocket", true);
            put("alaskan pipeline", true);
            put("anal", true);
            put("anilingus", true);
            put("anus", true);
            put("apeshit", true);
            put("arsehole", true);
            put("ass", true);
            put("asshole", true);
            put("assmunch", true);
            put("auto erotic", true);
            put("autoerotic", true);
            put("babeland", true);
            put("baby batter", true);
            put("baby juice", true);
            put("ball gag", true);
            put("ball gravy", true);
            put("ball kicking", true);
            put("ball licking", true);
            put("ball sack", true);
            put("ball sucking", true);
            put("bangbros", true);
            put("bareback", true);
            put("barely legal", true);
            put("barenaked", true);
            put("bastardo", true);
            put("bastinado", true);
            put("bbw", true);
            put("bdsm", true);
            put("beaner", true);
            put("beaners", true);
            put("beaver cleaver", true);
            put("beaver lips", true);
            put("bestiality", true);
            put("big black", true);
            put("big breasts", true);
            put("big knockers", true);
            put("big tits", true);
            put("bimbos", true);
            put("birdlock", true);
            put("bitch", true);
            put("bitches", true);
            put("black cock", true);
            put("blonde action", true);
            put("blonde on blonde action", true);
            put("Matthew whitehead", true);
            put("blowjob", true);
            put("blow job", true);
            put("blow your load", true);
            put("blue waffle", true);
            put("blumpkin", true);
            put("bollocks", true);
            put("bondage", true);
            put("boner", true);
            put("boob", true);
            put("boobs", true);
            put("booty call", true);
            put("brown showers", true);
            put("brunette action", true);
            put("bukkake", true);
            put("bulldyke", true);
            put("bullet vibe", true);
            put("bullshit", true);
            put("bung hole", true);
            put("bunghole", true);
            put("busty", true);
            put("butt", true);
            put("buttcheeks", true);
            put("butthole", true);
            put("camel toe", true);
            put("camgirl", true);
            put("camslut", true);
            put("camwhore", true);
            put("carpet muncher", true);
            put("carpetmuncher", true);
            put("chocolate rosebuds", true);
            put("circlejerk", true);
            put("cleveland steamer", true);
            put("clit", true);
            put("clitoris", true);
            put("clover clamps", true);
            put("clusterfuck", true);
            put("cock", true);
            put("cocks", true);
            put("coprolagnia", true);
            put("coprophilia", true);
            put("cornhole", true);
            put("coon", true);
            put("coons", true);
            put("creampie", true);
            put("cum", true);
            put("cumming", true);
            put("cunnilingus", true);
            put("cunt", true);
            put("darkie", true);
            put("date rape", true);
            put("daterape", true);
            put("deep throat", true);
            put("deepthroat", true);
            put("dendrophilia", true);
            put("dick", true);
            put("dildo", true);
            put("dirty pillows", true);
            put("dirty sanchez", true);
            put("doggie style", true);
            put("doggiestyle", true);
            put("doggy style", true);
            put("doggystyle", true);
            put("dog style", true);
            put("dolcett", true);
            put("domination", true);
            put("dominatrix", true);
            put("dommes", true);
            put("donkey punch", true);
            put("double dong", true);
            put("double penetration", true);
            put("dp action", true);
            put("dry hump", true);
            put("dvda", true);
            put("eat my ass", true);
            put("ecchi", true);
            put("ejaculation", true);
            put("erotic", true);
            put("erotism", true);
            put("escort", true);
            put("ethical slut", true);
            put("eunuch", true);
            put("faggot", true);
            put("fecal", true);
            put("felch", true);
            put("fellatio", true);
            put("feltch", true);
            put("female squirting", true);
            put("femdom", true);
            put("figging", true);
            put("fingerbang", true);
            put("fingering", true);
            put("fisting", true);
            put("foot fetish", true);
            put("footjob", true);
            put("frotting", true);
            put("fuck", true);
            put("fuck buttons", true);
            put("fuckin", true);
            put("fucking", true);
            put("fucktards", true);
            put("fudge packer", true);
            put("fudgepacker", true);
            put("futanari", true);
            put("gang bang", true);
            put("gay sex", true);
            put("genitals", true);
            put("giant cock", true);
            put("girl on", true);
            put("girl on top", true);
            put("girls gone wild", true);
            put("goatcx", true);
            put("goatse", true);
            put("god damn", true);
            put("gokkun", true);
            put("golden shower", true);
            put("goodpoop", true);
            put("goo girl", true);
            put("goregasm", true);
            put("grope", true);
            put("group sex", true);
            put("g-spot", true);
            put("guro", true);
            put("hand job", true);
            put("handjob", true);
            put("hard core", true);
            put("hardcore", true);
            put("hentai", true);
            put("homoerotic", true);
            put("honkey", true);
            put("hooker", true);
            put("hot carl", true);
            put("hot chick", true);
            put("how to kill", true);
            put("how to murder", true);
            put("huge fat", true);
            put("humping", true);
            put("incest", true);
            put("intercourse", true);
            put("jack off", true);
            put("jail bait", true);
            put("jailbait", true);
            put("jelly donut", true);
            put("jerk off", true);
            put("jigaboo", true);
            put("jiggaboo", true);
            put("jiggerboo", true);
            put("jizz", true);
            put("juggs", true);
            put("kike", true);
            put("kinbaku", true);
            put("kinkster", true);
            put("kinky", true);
            put("knobbing", true);
            put("leather restraint", true);
            put("leather straight jacket", true);
            put("lemon party", true);
            put("lolita", true);
            put("lovemaking", true);
            put("make me come", true);
            put("male squirting", true);
            put("masturbate", true);
            put("menage a trois", true);
            put("milf", true);
            put("missionary position", true);
            put("motherfucker", true);
            put("mound of venus", true);
            put("mr hands", true);
            put("muff diver", true);
            put("muffdiving", true);
            put("nambla", true);
            put("nawashi", true);
            put("negro", true);
            put("neonazi", true);
            put("nigga", true);
            put("nigger", true);
            put("nig nog", true);
            put("nimphomania", true);
            put("nipple", true);
            put("nipples", true);
            put("nsfw images", true);
            put("nude", true);
            put("nudity", true);
            put("nympho", true);
            put("nymphomania", true);
            put("octopussy", true);
            put("omorashi", true);
            put("one cup two girls", true);
            put("one guy one jar", true);
            put("orgasm", true);
            put("orgy", true);
            put("paedophile", true);
            put("paki", true);
            put("panties", true);
            put("panty", true);
            put("pedobear", true);
            put("pedophile", true);
            put("pegging", true);
            put("penis", true);
            put("phone sex", true);
            put("piece of shit", true);
            put("pissing", true);
            put("piss pig", true);
            put("pisspig", true);
            put("playboy", true);
            put("pleasure chest", true);
            put("pole smoker", true);
            put("ponyplay", true);
            put("poof", true);
            put("poon", true);
            put("poontang", true);
            put("punany", true);
            put("poop chute", true);
            put("poopchute", true);
            put("porn", true);
            put("porno", true);
            put("pornography", true);
            put("prince albert piercing", true);
            put("pthc", true);
            put("pubes", true);
            put("pussy", true);
            put("queaf", true);
            put("queef", true);
            put("quim", true);
            put("raghead", true);
            put("raging boner", true);
            put("rape", true);
            put("raping", true);
            put("rapist", true);
            put("rectum", true);
            put("reverse cowgirl", true);
            put("rimjob", true);
            put("rimming", true);
            put("rosy palm", true);
            put("rosy palm and her 5 sisters", true);
            put("rusty trombone", true);
            put("sadism", true);
            put("santorum", true);
            put("scat", true);
            put("schlong", true);
            put("scissoring", true);
            put("semen", true);
            put("sex", true);
            put("sexo", true);
            put("sexy", true);
            put("shaved beaver", true);
            put("shaved pussy", true);
            put("shemale", true);
            put("shibari", true);
            put("shit", true);
            put("shitty", true);
            put("shota", true);
            put("shrimping", true);
            put("skeet", true);
            put("slanteye", true);
            put("slut", true);
            put("s&m", true);
            put("smut", true);
            put("snatch", true);
            put("snowballing", true);
            put("sodomize", true);
            put("sodomy", true);
            put("spic", true);
            put("splooge", true);
            put("splooge moose", true);
            put("spooge", true);
            put("spread legs", true);
            put("spunk", true);
            put("strap on", true);
            put("strapon", true);
            put("strappado", true);
            put("strip club", true);
            put("style doggy", true);
            put("suck", true);
            put("sucks", true);
            put("suicide girls", true);
            put("sultry women", true);
            put("swastika", true);
            put("swinger", true);
            put("tainted love", true);
            put("taste my", true);
            put("tea bagging", true);
            put("threesome", true);
            put("throating", true);
            put("tied up", true);
            put("tight white", true);
            put("tit", true);
            put("tits", true);
            put("titties", true);
            put("titty", true);
            put("tongue in a", true);
            put("topless", true);
            put("tosser", true);
            put("towelhead", true);
            put("tranny", true);
            put("tribadism", true);
            put("tub girl", true);
            put("tubgirl", true);
            put("tushy", true);
            put("twat", true);
            put("twink", true);
            put("twinkie", true);
            put("two girls one cup", true);
            put("undressing", true);
            put("upskirt", true);
            put("urethra play", true);
            put("urophilia", true);
            put("vagina", true);
            put("venus mound", true);
            put("vibrator", true);
            put("violet wand", true);
            put("vorarephilia", true);
            put("voyeur", true);
            put("vulva", true);
            put("wank", true);
            put("wetback", true);
            put("wet dream", true);
            put("white power", true);
            put("wrapping men", true);
            put("wrinkled starfish", true);
            put("yellow showers", true);
            put("yiffy", true);
            put("zoophilia", true);

        }};
}
